### ISSUE TITLE
CopyMessage expects wrong result

### ISSUE THREAD

**Issue by OlegYch** [bot4s/telegram#410]
it should expect MessageId instead of Message https://core.telegram.org/bots/api#copymessage

**Comment by ex0ns** [comment]
Thanks for noticing it, would you mind opening a PR if you need it fixed soon ? Otherwise I will implement a fix later this month

 I think that we don't have a `MessageId` class yet (https://core.telegram.org/bots/api#messageid) as `CopyMessage` is the only method that returns those. `CopyMessage[s]` and `ForwardMessage[s]` (which are not implemented) will also need that.

**Comment by OlegYch** [comment]
@ex0ns submitted a pr
