### ISSUE TITLE
FutureSttpClient is unable to process polling repsonses from Telegram

### ISSUE THREAD

**Issue by ravinderpayal** [bot4s/telegram#96]
Just after bot is started, Log trace prints the following error after every polling attempt by SttPClient.

From the response, it seems telegram APIs are not giving the correct responses.

`[error, com.bot4s.telegram.clients.FutureSttpClient] RESPONSE 4ca5a90f-6867-48d9-86e8-fcaa1dc1e934 java.lang.IllegalArgumentException: requirement failed: Exactly one of the optional fields should be used`

**Comment by ravinderpayal** [comment]
I am using the standard example, weirdly I created a new bot and that's working but earlier ones are not working.

**Comment by dkartashev** [comment]
I had same problem. I used debugger to find out what's the problem. It's can't parse json from telegram. Fail somewhere in the circle library. Other bots libraries works fine on same telegram response.

can't parse polling results -> decide that it's not critical error -> immediatly try to add +1 to offset and retry telegram polling -> can't add 1 to offset, because on startup offset = None -> do same over and over, using all cpu that it can

Sorry, that i didn't report it earlier. I have few bots, and telegram response on which i can reproduce error. (finally i decided to switch to other bot library. Seems like all scala libraries have different problems, used java library at the end)

**Comment by ex0ns** [comment]
I'm unfortunately not able to reproduce the bug.
I've deployed a `RandomBot` from master and everything seems fine:

```scala
new RandomBot("my-token").run()
```

So here are a few questions:
1. Which version of the lib are you using ? 
2. Can you try to run a RandomBot successfully ?
3. Which scala version are you using (2.122 ? 2.12 ?)

Thank you for your help

**Comment by ravinderpayal** [comment]
`{"update_id":552151085,"my_chat_member":{"chat":{"id":-526921570,"title":"Deep Love","type":"group","all_members_are_administrators":true},"from":{"id":581926538,"is_bot":false,"first_name":"Ravinder","last_name":"Payal","username":"payalravinder","language_code":"en"},"date":1616011337,"old_chat_member":{"user":{"id":1645344913,"is_bot":true,"first_name":"Kluster Test Bot","username":"kluster_test_bot"},"status":"left"},"new_chat_member":{"user":{"id":1645344913,"is_bot":true,"first_name":"Kluster Test Bot","username":"kluster_test_bot"},"status":"member"}}}`

The bot fails for this response!

**Comment by ravinderpayal** [comment]
I found the reason of crash as well:

> March 9, 2021
> Bot API 5.1
> 
> Added two new update types
> 
> Added updates about member status changes in chats, represented by the class ChatMemberUpdated and the fields my_chat_member and chat_member in the Update class. The bot must be an administrator in the chat to receive chat_member updates about other chat members. By default, only my_chat_member updates about the bot itself are received.
https://core.telegram.org/bots/api

**Comment by ravinderpayal** [comment]
I am raising a PR to fix this, please accept

**Comment by ravinderpayal** [comment]
https://github.com/bot4s/telegram/pull/97

Please look into this
